Update libxml2 to 2.9.14
UPPAALModelChecker/utap pull request #19
Opened 2022-08-08 07:04 UTC by mikucionisaau

2022-08-08 16:11 UTC, mikucionisaau commented
Looks like the `libxml2` package from nix lacks cmake configuration :-(

2022-08-12 11:17 UTC, thorulf4 requested changes

2022-08-12 11:17 UTC, thorulf4 commented on .github/workflows/build.yml
> +#      run: nix build .\#utapWindows.x86_64-linux
This can probably just be removed

2022-08-12 13:42 UTC, thorulf4 approved these changes

2022-08-12 13:46 UTC, merged